services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task-management-sql
    ports:
      - "15433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass123!
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
